//
// FormatPartialUpdate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FormatPartialUpdate: Codable, JSONEncodable, Hashable {

    public var worldId: String?
    public var type: String?
    public var translations: [FormatTranslation]?

    public init(worldId: String? = nil, type: String? = nil, translations: [FormatTranslation]? = nil) {
        self.worldId = worldId
        self.type = type
        self.translations = translations
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case worldId
        case type
        case translations
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(worldId, forKey: .worldId)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(translations, forKey: .translations)
    }
}

