//
// RootServerBaseStatistics.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RootServerBaseStatistics: Codable, JSONEncodable, Hashable {

    public var serviceBodies: RootServerBaseStatisticsServiceBodies
    public var meetings: RootServerBaseStatisticsMeetings

    public init(serviceBodies: RootServerBaseStatisticsServiceBodies, meetings: RootServerBaseStatisticsMeetings) {
        self.serviceBodies = serviceBodies
        self.meetings = meetings
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case serviceBodies
        case meetings
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(serviceBodies, forKey: .serviceBodies)
        try container.encode(meetings, forKey: .meetings)
    }
}

