//
// RootServerBaseStatisticsServiceBodies.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RootServerBaseStatisticsServiceBodies: Codable, JSONEncodable, Hashable {

    public var numZones: Int
    public var numRegions: Int
    public var numAreas: Int
    public var numGroups: Int

    public init(numZones: Int, numRegions: Int, numAreas: Int, numGroups: Int) {
        self.numZones = numZones
        self.numRegions = numRegions
        self.numAreas = numAreas
        self.numGroups = numGroups
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case numZones
        case numRegions
        case numAreas
        case numGroups
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(numZones, forKey: .numZones)
        try container.encode(numRegions, forKey: .numRegions)
        try container.encode(numAreas, forKey: .numAreas)
        try container.encode(numGroups, forKey: .numGroups)
    }
}

