//
// RootServerBase.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RootServerBase: Codable, JSONEncodable, Hashable {

    public var sourceId: Int?
    public var name: String?
    public var url: String?
    public var statistics: RootServerBaseStatistics?
    public var serverInfo: String?
    public var lastSuccessfulImport: Date?

    public init(sourceId: Int? = nil, name: String? = nil, url: String? = nil, statistics: RootServerBaseStatistics? = nil, serverInfo: String? = nil, lastSuccessfulImport: Date? = nil) {
        self.sourceId = sourceId
        self.name = name
        self.url = url
        self.statistics = statistics
        self.serverInfo = serverInfo
        self.lastSuccessfulImport = lastSuccessfulImport
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sourceId
        case name
        case url
        case statistics
        case serverInfo
        case lastSuccessfulImport
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(sourceId, forKey: .sourceId)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(statistics, forKey: .statistics)
        try container.encodeIfPresent(serverInfo, forKey: .serverInfo)
        try container.encodeIfPresent(lastSuccessfulImport, forKey: .lastSuccessfulImport)
    }
}

