//
// RootServerBaseStatisticsMeetings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RootServerBaseStatisticsMeetings: Codable, JSONEncodable, Hashable {

    public var numTotal: Int
    public var numInPerson: Int
    public var numVirtual: Int
    public var numHybrid: Int
    public var numUnknown: Int

    public init(numTotal: Int, numInPerson: Int, numVirtual: Int, numHybrid: Int, numUnknown: Int) {
        self.numTotal = numTotal
        self.numInPerson = numInPerson
        self.numVirtual = numVirtual
        self.numHybrid = numHybrid
        self.numUnknown = numUnknown
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case numTotal
        case numInPerson
        case numVirtual
        case numHybrid
        case numUnknown
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(numTotal, forKey: .numTotal)
        try container.encode(numInPerson, forKey: .numInPerson)
        try container.encode(numVirtual, forKey: .numVirtual)
        try container.encode(numHybrid, forKey: .numHybrid)
        try container.encode(numUnknown, forKey: .numUnknown)
    }
}

