//
// SettingsUpdate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Partial update object - include only the settings you want to update */
public struct SettingsUpdate: Codable, JSONEncodable, Hashable {

    public var googleApiKey: String?
    public var changeDepthForMeetings: Int?
    public var defaultSortKey: String?
    public var language: String?
    public var defaultDurationTime: String?
    public var regionBias: String?
    public var distanceUnits: String?
    public var meetingStatesAndProvinces: [String]?
    public var meetingCountiesAndSubProvinces: [String]?
    public var searchSpecMapCenterLongitude: Float?
    public var searchSpecMapCenterLatitude: Float?
    public var searchSpecMapCenterZoom: Int?
    public var numberOfMeetingsForAuto: Int?
    public var autoGeocodingEnabled: Bool?
    public var countyAutoGeocodingEnabled: Bool?
    public var zipAutoGeocodingEnabled: Bool?
    public var defaultClosedStatus: Bool?
    public var enableLanguageSelector: Bool?
    public var includeServiceBodyEmailInSemantic: Bool?
    public var bmltTitle: String?
    public var bmltNotice: String?
    public var formatLangNames: AnyCodable?

    public init(googleApiKey: String? = nil, changeDepthForMeetings: Int? = nil, defaultSortKey: String? = nil, language: String? = nil, defaultDurationTime: String? = nil, regionBias: String? = nil, distanceUnits: String? = nil, meetingStatesAndProvinces: [String]? = nil, meetingCountiesAndSubProvinces: [String]? = nil, searchSpecMapCenterLongitude: Float? = nil, searchSpecMapCenterLatitude: Float? = nil, searchSpecMapCenterZoom: Int? = nil, numberOfMeetingsForAuto: Int? = nil, autoGeocodingEnabled: Bool? = nil, countyAutoGeocodingEnabled: Bool? = nil, zipAutoGeocodingEnabled: Bool? = nil, defaultClosedStatus: Bool? = nil, enableLanguageSelector: Bool? = nil, includeServiceBodyEmailInSemantic: Bool? = nil, bmltTitle: String? = nil, bmltNotice: String? = nil, formatLangNames: AnyCodable? = nil) {
        self.googleApiKey = googleApiKey
        self.changeDepthForMeetings = changeDepthForMeetings
        self.defaultSortKey = defaultSortKey
        self.language = language
        self.defaultDurationTime = defaultDurationTime
        self.regionBias = regionBias
        self.distanceUnits = distanceUnits
        self.meetingStatesAndProvinces = meetingStatesAndProvinces
        self.meetingCountiesAndSubProvinces = meetingCountiesAndSubProvinces
        self.searchSpecMapCenterLongitude = searchSpecMapCenterLongitude
        self.searchSpecMapCenterLatitude = searchSpecMapCenterLatitude
        self.searchSpecMapCenterZoom = searchSpecMapCenterZoom
        self.numberOfMeetingsForAuto = numberOfMeetingsForAuto
        self.autoGeocodingEnabled = autoGeocodingEnabled
        self.countyAutoGeocodingEnabled = countyAutoGeocodingEnabled
        self.zipAutoGeocodingEnabled = zipAutoGeocodingEnabled
        self.defaultClosedStatus = defaultClosedStatus
        self.enableLanguageSelector = enableLanguageSelector
        self.includeServiceBodyEmailInSemantic = includeServiceBodyEmailInSemantic
        self.bmltTitle = bmltTitle
        self.bmltNotice = bmltNotice
        self.formatLangNames = formatLangNames
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case googleApiKey
        case changeDepthForMeetings
        case defaultSortKey
        case language
        case defaultDurationTime
        case regionBias
        case distanceUnits
        case meetingStatesAndProvinces
        case meetingCountiesAndSubProvinces
        case searchSpecMapCenterLongitude
        case searchSpecMapCenterLatitude
        case searchSpecMapCenterZoom
        case numberOfMeetingsForAuto
        case autoGeocodingEnabled
        case countyAutoGeocodingEnabled
        case zipAutoGeocodingEnabled
        case defaultClosedStatus
        case enableLanguageSelector
        case includeServiceBodyEmailInSemantic
        case bmltTitle
        case bmltNotice
        case formatLangNames
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(googleApiKey, forKey: .googleApiKey)
        try container.encodeIfPresent(changeDepthForMeetings, forKey: .changeDepthForMeetings)
        try container.encodeIfPresent(defaultSortKey, forKey: .defaultSortKey)
        try container.encodeIfPresent(language, forKey: .language)
        try container.encodeIfPresent(defaultDurationTime, forKey: .defaultDurationTime)
        try container.encodeIfPresent(regionBias, forKey: .regionBias)
        try container.encodeIfPresent(distanceUnits, forKey: .distanceUnits)
        try container.encodeIfPresent(meetingStatesAndProvinces, forKey: .meetingStatesAndProvinces)
        try container.encodeIfPresent(meetingCountiesAndSubProvinces, forKey: .meetingCountiesAndSubProvinces)
        try container.encodeIfPresent(searchSpecMapCenterLongitude, forKey: .searchSpecMapCenterLongitude)
        try container.encodeIfPresent(searchSpecMapCenterLatitude, forKey: .searchSpecMapCenterLatitude)
        try container.encodeIfPresent(searchSpecMapCenterZoom, forKey: .searchSpecMapCenterZoom)
        try container.encodeIfPresent(numberOfMeetingsForAuto, forKey: .numberOfMeetingsForAuto)
        try container.encodeIfPresent(autoGeocodingEnabled, forKey: .autoGeocodingEnabled)
        try container.encodeIfPresent(countyAutoGeocodingEnabled, forKey: .countyAutoGeocodingEnabled)
        try container.encodeIfPresent(zipAutoGeocodingEnabled, forKey: .zipAutoGeocodingEnabled)
        try container.encodeIfPresent(defaultClosedStatus, forKey: .defaultClosedStatus)
        try container.encodeIfPresent(enableLanguageSelector, forKey: .enableLanguageSelector)
        try container.encodeIfPresent(includeServiceBodyEmailInSemantic, forKey: .includeServiceBodyEmailInSemantic)
        try container.encodeIfPresent(bmltTitle, forKey: .bmltTitle)
        try container.encodeIfPresent(bmltNotice, forKey: .bmltNotice)
        try container.encodeIfPresent(formatLangNames, forKey: .formatLangNames)
    }
}

