//
// Token.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Token: Codable, JSONEncodable, Hashable {

    public var accessToken: String
    public var expiresAt: Int
    public var tokenType: String
    public var userId: Int

    public init(accessToken: String, expiresAt: Int, tokenType: String, userId: Int) {
        self.accessToken = accessToken
        self.expiresAt = expiresAt
        self.tokenType = tokenType
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accessToken = "access_token"
        case expiresAt = "expires_at"
        case tokenType = "token_type"
        case userId = "user_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(accessToken, forKey: .accessToken)
        try container.encode(expiresAt, forKey: .expiresAt)
        try container.encode(tokenType, forKey: .tokenType)
        try container.encode(userId, forKey: .userId)
    }
}

