//
// UserPartialUpdate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserPartialUpdate: Codable, JSONEncodable, Hashable {

    public var username: String?
    public var type: String?
    public var displayName: String?
    public var description: String?
    public var email: String?
    public var ownerId: Int?
    public var password: String?

    public init(username: String? = nil, type: String? = nil, displayName: String? = nil, description: String? = nil, email: String? = nil, ownerId: Int? = nil, password: String? = nil) {
        self.username = username
        self.type = type
        self.displayName = displayName
        self.description = description
        self.email = email
        self.ownerId = ownerId
        self.password = password
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case username
        case type
        case displayName
        case description
        case email
        case ownerId
        case password
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(username, forKey: .username)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(displayName, forKey: .displayName)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(ownerId, forKey: .ownerId)
        try container.encodeIfPresent(password, forKey: .password)
    }
}

