name: bmlt
targets:
  bmlt:
    type: framework
    platform: iOS
    deploymentTarget: "11.0"
    sources: [bmlt]
    info:
      path: ./Info.plist
      version: 1.0.2
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: AnyCodable
