//
// FormatTranslation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FormatTranslation: Codable, JSONEncodable, Hashable {

    public var key: String
    public var name: String
    public var description: String
    public var language: String

    public init(key: String, name: String, description: String, language: String) {
        self.key = key
        self.name = name
        self.description = description
        self.language = language
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case key
        case name
        case description
        case language
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(key, forKey: .key)
        try container.encode(name, forKey: .name)
        try container.encode(description, forKey: .description)
        try container.encode(language, forKey: .language)
    }
}

